### ISSUE TITLE
Lots of jobs for preview initializing even though it is turned off 

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#107]
![image](https://user-images.githubusercontent.com/139910/41603368-1eff8bca-73dd-11e8-9af4-eb7155f254b5.png)

![image](https://user-images.githubusercontent.com/139910/41603429-38c5c01a-73dd-11e8-91cd-a5cef918c44c.png)

IMHO this job should not run, if preview is turned off.

**Comment by vogella** [comment]
I actually had to kill Eclipse to get rid of these jobs.

**Comment by de-jcup** [comment]
Ups...  So 1.0.0 will wait and a bugfix release will come up.

**Comment by de-jcup** [comment]
Hm.. forget my last message 1.0.0 is nearly ready so I will fix it with 1.0.0

**Comment by de-jcup** [comment]
### Explantion when and why a rebuild is okay
I just looked inside the code: The build job is always triggered on persistent changes (no matter if preview is enabled or not)  because internal and external preview files are both generated (they are nearly the same, only the auto-refresh integration is special in external variant). So you can always refresh your opened browser and got the newest result (or let it be done by the auto refresh function).

### I do not have those behaviour
I am using Editor with plugin 0.10.1 at eclipse oxygen 4.7.3a on windows 7 with multiple opened documents, also in "hide preview" mode and I do not have those problems.

### Way to reproduce
Have you an example workflow how to simulate/enable such a situation? I did try to reproduceit  but found no way.

**Comment by de-jcup** [comment]
I tried out to reproduce problem, even with an eclipse startup with multiple asciidoc editor files visible on screen like:

![image](https://user-images.githubusercontent.com/11644753/41655380-f7a27a1e-748c-11e8-871b-c7fa9469f00c.png)

and also in internal preview mode:

![image](https://user-images.githubusercontent.com/11644753/41655427-1ab7f1f0-748d-11e8-942f-354f92e29193.png)

I was not able to reproduce the problem.

But to prevent an eclipse restart in those situations I implemented a cancel mechanism in https://github.com/de-jcup/eclipse-asciidoctor-editor/commit/65af078a41003f1e0dfaa1c998ba2935b6cb3de5 

Every build action can now be canceled separately:
(in next example I canceled the middle job from picture before)

![image](https://user-images.githubusercontent.com/11644753/41655540-7b26a3d8-748d-11e8-8130-3a160538d7cd.png)

**Comment by de-jcup** [comment]
@vogella I close this issue and release V1.0.0 on marketplace in next time. If you got such problems with V1.0.0 again please create a new issue and reference this one. Thx.

**Comment by de-jcup** [comment]
@vogella : just released `1.0.0` to marketplace.
