### ISSUE TITLE
Synchronized scrolling

### ISSUE THREAD

**Issue by sjaeckel** [de-jcup/eclipse-asciidoctor-editor#126]
It'd be awesome if there would be the possibility to synchronize the views of the adoc document and the  preview when scrolling.

**Comment by de-jcup** [comment]
It is difficult to exactly identify the position of every part in rendered output html. 

With #124 I wanted to sync at least the headlines (because always identifiable) in outline + quick outline.

When rendering the output (happens on save actions, startup or refresh) it could also be tried to estimate the position by following algorithm:

- get current cursor location in text
- whats next headline (or if no headline use html body as reference...)
- try to find the exact text in document after this headline in source
  -  if available try to identifiy an element there...
  - if not available use the found headline id

Shall use same preference flag "automatic scrolling" as used in #124 

There should be also a action inside toolbar (next to "go top") which does same as described above

**Comment by de-jcup** [comment]
With #124  I implemented a good working solution for anchors and headlines: Move the cursor to a line containing a headline  or a anchor and the internal preview will scroll to this position.

So maybe this is good enough.

The previous ideas about scanning text etc. are good ideas, but using multiple includes in a file could result in heavy calculations.

Maybe in future includes etc. will be handled as mentioned above, but not in Milestone 1.1.0.

@sjaeckel : Please checkout the scroll handling when 1.1.0 is released and give me feedback if the solution in #124 is good enough or not.

**Comment by de-jcup** [comment]
@sjaeckel : I just released 1.1.0 on marketplace, scroll feature is shown in video at https://www.youtube.com/watch?v=VhTog9iwySs

**Comment by sjaeckel** [comment]
I can confirm that this works most of the time as long as you don't use custom ID's with `#` as defined in https://asciidoctor.org/docs/user-manual/#custom-ids to reference to a chapter/section

This seems to break the implementation:

```
[#FOO]
= BAR
```

whereas this seems to be okay

```
[[FOO]]
= BAR
```

**Comment by de-jcup** [comment]
@sjaeckel : I created another issue for this #154 . It will be in next hotfix milestone (1.1.1)

**Comment by de-jcup** [comment]
Done now with #154
