### ISSUE TITLE
Preview is initializing even though no preview is set

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#143]
![docu - tutorials scripts-rcp-380_exercise_dialogs_wizards adoc - eclipse sdk _510](https://user-images.githubusercontent.com/139910/44873678-21b0aa80-ac99-11e8-87e2-2f26ca5fa1e5.png)

I frequently see the message in the right footer that the Asciidoctor preview is initializing even though I have turned that off. This seem also to be a heavy operation as it significantly slows done Eclipse.

**Comment by vogella** [comment]
Even if I close the editors, this seem to continue to run.

![image](https://user-images.githubusercontent.com/139910/44873961-f8444e80-ac99-11e8-9383-7c0fcca21b45.png)

**Comment by de-jcup** [comment]
Hello @vogella , Yes, the initializing parts are a little bit heavy because there asciidoctor will be called (heaviest one), resources copied and some parts initialized.

> I frequently see the message in the right footer that the Asciidoctor preview is initializing even though I have **turned that off.** This seem also to be a heavy operation as it significantly slows done Eclipse.

I think with "turn off" you are talking about the external preview don't you? 
Currently asciidoctor editor does always create a new preview - no matter if you are using the internal preview area or not.

Maybe it would be a good way to create and initialize the asciidoctor on changes only when:
- internal preview is used (so still automatically)
or
- "open asciidoctor ouptut in external browser" action is called" (maybe with an "opt-in" preference which is per default turned off, otherwise the "auto refresh" setup for external views in preferences make no longer sense)

What do you think about this approach ?

**Comment by vogella** [comment]
|> I think with "turn off" you are talking about the external preview don't you?

Yes, here is my setting.

![image](https://user-images.githubusercontent.com/139910/44985963-8d896080-af82-11e8-89bb-05a9e0e52c17.png)

> What do you think about this approach?

The approach sounds good to me. I personally never use the preview from your editor so if that work can be avoided, that sounds good.

**Comment by de-jcup** [comment]
Per default auto build is now disabled for external preview mode.

can be configured:

![image](https://user-images.githubusercontent.com/11644753/45504238-97347480-b789-11e8-90cf-211315155b7b.png)

**Comment by de-jcup** [comment]
Reopened, because editor activation still created all files - and this was not wanted.

**Comment by de-jcup** [comment]
Now no files (except an empty temp folder)  are created in case of external preview mode + disabled auto build for external preview.

Means: as long as you are not pressing the "refresh" or the "show in external browser" button no files are generated.
