### ISSUE TITLE
PlantUML stdlib support

### ISSUE THREAD

**Issue by r1m** [de-jcup/eclipse-asciidoctor-editor#155]
It seems that plantUML editor does not support [PlantUml standard lib](http://plantuml.com/stdlib)

```
@startuml AWS icon test
!include <aws/common>
!include <aws/ApplicationServices/AmazonAPIGateway/AmazonAPIGateway>
AMAZONAPIGATEWAY(gateway,"",rectangle)

@enduml
```
It works with commandline ``plantuml aws-test.puml`` and with maven plugin, but not inside the preview : 
```
Cannot include D:\Users\me\AppData\Local\Temp\asciidoctor-editor-temp\editor_234023409\<aws\common>
```

**Comment by de-jcup** [comment]
The plantuml editor of asciidoctor editor simply wraps up the plantuml file into a temorary asciidoc file.
At rendering time the temporary folder is set as root and asciidocj is started which calls asciidoctor itself.

So maybe asciidoctor itself has got a problem here.

Have build your puml file with maven directly or did you use maven + asciidoctor to build the output?

**Comment by r1m** [comment]
I use the maven asciidoctor plugin with diagram inside asciidocs.
It looks like the path resolution is not working.
There was an issue on asciidoctor-diagram : https://github.com/asciidoctor/asciidoctor-diagram/issues/186

**Comment by de-jcup** [comment]
Thank for searching the issue - this is the reason why its not working.
This was fixed in 1.5.10  and should be fixed with using new version, but...

1. Integration of new lib version
This is not as easy as it sound because its always a little bit tricky to get ruby things working with OSGI (for details please read https://github.com/de-jcup/eclipse-asciidoctor-editor/blob/master/asciidoctor-editor-libs/diagram/README.md )
and i am not sure if its compatible with asciidoctorj-1.5.6 what is currently used as embedded variant, but I would give it a try.

2. Version not available
Sorrowly https://mvnrepository.com/artifact/org.asciidoctor/asciidoctorj-diagram
lists only up to diagram 1.5.9 , the fix is inside 1.5.10

@mojavelinux : Is there a plan when asciidoctorj-diagram.1.5.10.jar will be released (on mvn central) ?

Of course it would be nicer to have this inside embedded version but if there is no simple fix for embedded variant maybe the feature https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/147 which is planned for Version 1.2.0 could fix the problem too, by switching to installed asciidoctor version?

**Comment by mojavelinux** [comment]
> Is there a plan when asciidoctorj-diagram.1.5.10.jar will be released (on mvn central) ?

@de-jcup The person you want to talk to is @robertpanzer (and perhaps input from @pepijnve if there are questions about upstream).

**Comment by de-jcup** [comment]
@robertpanzer Is there a plan when asciidoctorj-diagram.1.5.10.jar will be released (on mvn central) ?

**Comment by robertpanzer** [comment]
I wasn’t aware that there’s a new version. I’m out this and next week, but should be able to release a new version sometime after the 8th if everything goes smooth.

**Comment by robertpanzer** [comment]
I just released asciidoctorj-diagram 1.5.10. It can take a while until the files are on Maven Central, but they are already available via Bintray.
Please let me know if this fixes your problem.

**Comment by mojavelinux** [comment]
Thank you @robertpanzer!

**Comment by de-jcup** [comment]
hmm... having problems to integrate 1.5.10. Internal file structure has changed. Did add all new jars etc., updated OSGI wrapper parts etc. but got 

```
org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- asciidoctor-diagram
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1040)
	at RUBY.require(classpath:/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54)
	at RUBY.(root)(<script>:1)
```
So I will keep on implemeting #147 . If its fast enough to use external installation, its not necessary to update default (much pain with OSGI...)

**Comment by de-jcup** [comment]
Sorrowly this is too much pain (OSGI, JRUBY, + dependencies).
#147 is nearly feature complete implemented and with using installed asciidoc the problem is solved:

![image](https://user-images.githubusercontent.com/11644753/46728187-842a9c80-cc82-11e8-9c3e-a24fdd4d1c42.png)

So the embedded variant will be as is but you can solve your problem with using the installed version in upcoming version 1.2.0 

So I close the issue.

**Comment by r1m** [comment]
Great ! Thanks for your work

**Comment by de-jcup** [comment]
@robertpanzer Thank you robert for uploading the new jars to maven central. I tried it out, but I was not able to get it working again with OSGI+JRUBY+AsciidoctorJ. But thank you for your help.
