### ISSUE TITLE
I just wonder

### ISSUE THREAD

**Issue by paulvi** [de-jcup/eclipse-asciidoctor-editor#18]
I just wonder why are you doing so many good things for free

**Comment by de-jcup** [comment]
Because I love eclipse and do not want to use intellij ;-)

I am using eclipse since over 13 years now without paying anything for it - because its open source. I am not using IntelliJ (its a very good IDE but I am not comfortable with it). 

Maybe this is my little contribution to "make eclipse great again".

**Comment by paulvi** [comment]
Hi, do you have thoughts for better wording on http://with-eclipse.github.io/

**Comment by de-jcup** [comment]
Hm... maybe a "...powered by eclipse" would be nice.

By the way: At least the images could be upgraded - the new eclipse logo looks better  / more modern.

**Comment by paulvi** [comment]
That is https://github.com/with-Eclipse/with-eclipse.github.io/issues/1
