### ISSUE TITLE
"Preview file generation timed out, so preview not available." 

### ISSUE THREAD

**Issue by mgruschi-arz** [de-jcup/eclipse-asciidoctor-editor#193]
Preview file generation failes when name of adoc-File contains umlauts like ä,ö,ü.

Example error from eclipse's problem/markers view:

AsciidoctorCoreException: (Errno::EACCES) C:/Users/<user>/AppData/Local/Temp/asciidoctor-editor-temp/project_<eclipse-project>477157937/576408162_hidden-editorfile_Umlauts-???.html	Umlauts-äöü.adoc	/<eclipse-project>	\<eclipse-project>\Umlauts-äöü.adoc	AsciiDoctoreditor script problem

**Comment by de-jcup** [comment]
Hmmm funny - works with Linux without any problems... tried out with Windows 7 and have same failure... 

Will fix this for windows.

**Comment by de-jcup** [comment]
The problem happens only on embedded asciidoctor variant but not on installed one.

**Reason:**
The problem is java launch of eclipse and it's used `file.encoding` system property in combination with `java.util.File#getName()`
On windows systems its often set to `cp1252`which is windows standard charset. Asciidoctor in embedded variant treats name as UTF8-String.

This happens only on first file name. Includes having umlauts are not influenced.

**Solution:**
The filename of hidden asciidoc file contains editorId as a unique key, followed by origin name to make it easier to identify which edited file is meant. One option would be to use `java.nio` parts to get rid of the problem. Another, easier workaround is to replace the file name parts of hidden asciidoc file with ascii characters only - will use this approach.
