### ISSUE TITLE
cannot install or update to Asciidoctor Editor 1.4.3 if using C++ Eclipse distribution

### ISSUE THREAD

**Issue by anb0s** [de-jcup/eclipse-asciidoctor-editor#204]
> Eclipse IDE for C/C++ Developers
> Version: 2019-03 (4.11.0)
> Build id: 20190314-1200

Error during installation because of missing dependencies:

```
 Your original request has been modified.
  "Asciidoctor Editor" is already installed, so an update will be performed instead.
Cannot complete the install because one or more required items could not be found.
  Software being installed: Asciidoctor Editor 1.4.3 (de.jcup.asciidoctoreditor.feature.group 1.4.3)
  Missing requirement: Asciidoctor Converter 1.0.1 (de.jcup.asciidoctor.converter 1.0.1) requires 'osgi.bundle; org.junit 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Asciidoctor Editor 1.4.3 (de.jcup.asciidoctoreditor.feature.group 1.4.3)
    To: org.eclipse.equinox.p2.iu; de.jcup.asciidoctor.converter [1.0.1,1.0.1]

```

**Comment by de-jcup** [comment]
Thanx for reporting. Added accidently not junit lib but junit plugin as dependency. OMG. 1.4.x is not my release...

**Comment by de-jcup** [comment]
@anb0s just released 1.4.4 on marketplace which adresses the problem. Please close your eclipse and start new (because otherwise marketplace client cache will not show you 1.4.4 some time), open marketplace client and install update of 1.4.4... 

Installation should now work as expected also for C++ environment.
Please give me feedback if it works now for you.

By the way - having all this nuisance about the update with the converter you maybe interested about the benefits. If so, have a look at https://github.com/de-jcup/eclipse-asciidoctor-editor/wiki/Converter

**Comment by anb0s** [comment]
Thanks! Now it looks good :)

Btw. you can refresh the update site cache with "Reload":
![image](https://user-images.githubusercontent.com/95811/56042731-06804000-5d3c-11e9-8157-6da347e9a94f.png)

and then reopen the update manager again:
![image](https://user-images.githubusercontent.com/95811/56042764-17c94c80-5d3c-11e9-9f49-6d5f6df0300c.png)

Then it works without Eclipse restart.

I will work with the version and converter from md to adoc and report...

**Comment by de-jcup** [comment]
Oh nice. Thanx
