### ISSUE TITLE
Link source editor and preview

### ISSUE THREAD

**Issue by Fuzzo** [de-jcup/eclipse-asciidoctor-editor#283]
When the source file is saved, the editor always scroll to beginning. Wuould be useful to have a function that automatically scroll the preview at source cursor point level.

**Comment by de-jcup** [comment]
What exactly "scrolls to beginning" ? I am having problems to understand/reproduce

## My attempt to reproduce
Lets see how I work:
1. I am using ASP Server for rendering
2. I open a big asciidoc file containing much text with many headlines
3. My asciidoctor editor is in split mode vertical, means left editor, right preview
4. I click to one tof the headlines inside editor, so preview tries find it by its ID and scrolls to this position.
5. When I change some text, e.g. the headline and save the file I am still at the same position in preview, only preview has been reloaded.

I am working with Linux, Ubuntu based, using currently diverse Eclipse variants, up to 2019-03

## About already implemented auto scrolling in editor
So I cannot reproduce the problem. Also there is a scroll mechanism for asiidoctor editor: just click on the headlines inside your editor and preview should scroll to correct position. Only includes parts are ignored - because editor has no IDs for this content

## Suggestion
### Create a test file inside eclipse-asciidoctor-testprojects
If you have a file where your described situation always happens, please fork https://github.com/de-jcup/eclipse-asciidoctor-testprojects repository, select a suitable testproject (like your own setup) and add there a file which does reproduce the problem. After this, please create an PR and I will merge it into.

So it's easier for communication.

### Tell me your setup
- OS
- Java Version
- Eclipse Version
- Encoding used to start eclipse (E.g. UTF-8, CP1252, ...)
