### ISSUE TITLE
bintray will shut down

### ISSUE THREAD

**Issue by Bananeweizen** [de-jcup/eclipse-asciidoctor-editor#333]
Please move the update site: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by de-jcup** [comment]
@Bananeweizen thanx a lot !!! I am currently maintaining ~10 eclipse plugins and all are currently hosted at Bintray.

@vogella - I adopted your bintray upload scripts from https://github.com/vogellacompany/bintray-publish-p2-updatesite a lot ... maybe this is interesting for you as well?

**Comment by de-jcup** [comment]
I created https://stackoverflow.com/questions/66050231  as a central point to address the problem.

I also added there a possible solution/workaround with GitHub pages at https://stackoverflow.com/questions/66050231/eclipse-plugin-update-site-hosting-alternative-to-bintray/66050232#66050232 

**Update: 2021-02-05**
Unfortunately stackoverflow rejected my question ..

<img src="https://user-images.githubusercontent.com/11644753/107010478-b0914d80-6796-11eb-898b-f8e37a87fe2d.png" width="50%" />


so I copied/moved the question to
https://serverfault.com/questions/1052475/eclipse-plugin-update-site-hosting-alternative-to-bintray
and deleted the stackoverflow question.

**Comment by akurtakov** [comment]
https://wiki.eclipse.org/Tycho/Release_Notes/2.3#A_mojo_to_remap_Maven_artifacts_to_Maven_URLs_in_artifact_repository might be interesting aid for the issue but not a solution on it's own. So deploy bundles to maven central and reuse them directly from there is in the works but p2 metadata would have to live somewhere else.

**Comment by de-jcup** [comment]
@paulvi : Do you already have any good alternative for p2 repo hosting? If so please add a comment here or at https://serverfault.com/questions/1052475/eclipse-plugin-update-site-hosting-alternative-to-bintray . Thx a lot.

**Comment by de-jcup** [comment]
As of lack of alternatives, I decided to use the github pages approach.

- I have migrated now batch, bash and yaml editor to github pages approach. With https://github.com/de-jcup/p2-updatesite-github-pages-automation/issues/1 there is a default approach which must only be copied to rootfolder. It only needs a mirror 
 repository named "update-site-eclipse-asciidoctor-editor" all other things work out-of-the-box.
- I have tried out the other plugins first, because they are much smaller. 
- **Asciidoctor Editor will follow soon** (I will try to fix some issues and make some improvements before doing the migration, so
  users  will have a benefit)

**Comment by Bananeweizen** [comment]
You already did the work. Thanks for that. http://www.lorenzobettini.it/2021/03/publishing-an-eclipse-p2-composite-repository-on-github-pages/ was just published, maybe you want to verify your steps with that article.

**Comment by SaMuellerDLR** [comment]
Hi, bintray seems to now be officially out of service. I see you have already migrated a lot of your p2 update sites to github pages (already using the new yaml editor one!) Great work! In your last comment I see some mentions about you fixing some last issues, do you forsee any problems using the same approach for the asciidoctor-editor?

**Comment by dejan2609** [comment]
It is a scheduled maintenance / brownout session : https://status.bintray.com/incidents/3kkmd0pnsg9r

**Comment by de-jcup** [comment]
@SaMuellerDLR  - I am still refactoring some parts inside the plugin - so I will get rid of the image location problems (users will be able to define image location by configuration files (see #338 )  but currently there are still some issues. And I am very busy at the moment.

I will adopt the Asciidoctor Editor also with my new p2 approach . But currently I am very busy and have not much time  - I hope it gets better in the future.


Writing these lines and adding this link:  see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
I wanted to mention that bintray will provide repository access until next year (2022) - I read an update message on the website one ore two month ago, but now there is following:

> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.
> 
> UPDATE 2/28/2021: To better support the community in this migration, JFrog has extended the JCenter new package versions submission deadline through March 31st 2021.
> 

and inside the table below (at the linked homepage)

> Now | Bintray, JCenter, GoCenter, and ChartCenter service continues.

This is ... very confusing .. because I thought they had announced that there is read only access until next year (2022).

But okay. I will try to fix some issues - at least https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/340 and provide a new asciidoctor plugin version asap.

**Comment by Bananeweizen** [comment]
don't be confused by the "now" part in the table. that's in relation to the date the original article was published. the updates at the top have not been factored into that table. basically the last entry in the table is the only one being valid as of _now_.

**Comment by de-jcup** [comment]
I just tested - and most plugins are no longer hosted at https://bintray.com/de-jcup ! Only 3 repositories are listed: `yamleditor`, `sqleditor`, `test-generic` but not this one.

OMG. I have no idea why this happened - it seems this is an issue at bintray. 
Nevertheless I will migrate other plugins as soon as possible and provide a new update url at marketplace.

**Comment by de-jcup** [comment]
created https://github.com/de-jcup/update-site-eclipse-asciidoctor-editor

**Comment by mypsycho** [comment]
Thanks a lot for the fast reaction.

**Comment by dhendriks** [comment]
> created https://github.com/de-jcup/update-site-eclipse-asciidoctor-editor

It seems to be empty still, with only an `index.md` file. Any idea when an actual release will be there?

**Comment by de-jcup** [comment]
I just deployed Version 2.3.0 to eclipse marketplace. Just do the update by the eclipse marketplace client  (as usual).
The update site will automatically be updated and the new version fetched.
