### ISSUE TITLE
PlantUML version outdated

### ISSUE THREAD

**Issue by wlfbck** [de-jcup/eclipse-asciidoctor-editor#336]
I'm trying to use https://github.com/plantuml-stdlib/C4-PlantUML which uses tags which are not available yet in the PlantUML version you are using.

asciidoctor-diagram itself is already using the newer version, so i'm not sure if you just need to update that dependency.

**Comment by de-jcup** [comment]
With Version 2.3.0 there was a new version of ASP used - see https://github.com/de-jcup/asp/releases/tag/v1.2.0
With this https://github.com/de-jcup/asp/issues/32 was done where newer dependencies are used.

I tried out the examples with V2.3.0 and it did still not work out of the box.

But in https://github.com/de-jcup/STTK we do also work with C4 plantuml files. And this worked well.
As a workaround we stored the C4 files locally (inside git...) -see https://github.com/de-jcup/STTK/tree/master/snippets

Does Plantuml now provide these parts directly?

**Comment by de-jcup** [comment]
The current used version of asciidoctorj-diagram is 2.1.2
This version uses JRuby parts having plantuml 1.2021.2 inside:

Path inside asp-server-asciidoctorj-dist.jar (when using ASP for rendering)  `/gems/asciidoctor-diagram-plantuml-1.2021.2/lib/asciidoctor-diagram/plantuml/`

**Comment by charleech** [comment]
FYI,

The `asciidoctor-diagram` has updated the `plantuml` to version `1.2021.7` as the following: -

* https://github.com/asciidoctor/asciidoctor-diagram/issues/357
* https://rubygems.org/gems/asciidoctor-diagram-plantuml

Anyhow it has not been released since Apr, 2021 as the following: -

* https://github.com/asciidoctor/docker-asciidoctor/issues/207

I'm also looking forward to using it within the latest and greatest `Eclipse-Asciidoctor-Plugin`  as well. :smile:

**Comment by pepijnve** [comment]
Another FYI. Starting with asciidoctor-diagram 2.1.0 the embedded versions of PlantUML and Ditaa are split off into separate gems. Those can (and are) updated without introducing a new version of asciidoctor-diagram. If you use a dependency manager like bundlr you'll need to update the dependency graph to pull in the most recent versions of those jar wrapper gems.

This applies to the Ruby version of the gem though. The ASP project is using [asciidoctorj-diagram](https://github.com/asciidoctor/asciidoctorj-diagram), which is a repackaging of the upstream gem and its dependencies for asciidoctorj. You'll have to ask the maintainers of that project to make a new build in order to get the updated PlantUML version.

**Comment by charleech** [comment]
@de-jcup 

I apologize for ping and disturbing you. I would like to inform you that there is an update on the topic discussing about the `asciidoctorj-diagram` release plan at https://asciidoctor.zulipchat.com/ as the following

> Robert Panzer 20:33
Sorry for not acting for such a long time. I've started a PR trying to split out the plantuml and ditaa extensions into separate jars copying the structure of asciidoctor-diagram. I've published `org.asciidoctor:asciidoctorj-diagram-plantuml:1.2021.8` and `org.asciidoctor:asciidoctorj-diagram-ditaamini:1.0.0` to https://oss.sonatype.org/content/repositories/orgasciidoctor-1268
> Could you please check if this works for you when you add the asciidoctorj-diagram.plantuml.jar to your imports?
The corresponding PR is at https://github.com/asciidoctor/asciidoctorj-diagram/pull/19
If JRuby picks the right dependency then there should be no need to publish a new asciidoctorj-diagram as long as there is no other update.

I'm not sure if you may have time to look at this or not.

**Comment by de-jcup** [comment]
@charleech, @pepijnve  : Thank you very much for the input. I will try to fix it in next version.
_(sorry for the late response)_

**Comment by de-jcup** [comment]
https://github.com/de-jcup/asp/releases/tag/v1.3.0 does now include the new versions. Will update asp dependencies on deployment.
