### ISSUE TITLE
Missing JRE with Eclipse JustJ JDK

### ISSUE THREAD

**Issue by dkaiser59** [de-jcup/eclipse-asciidoctor-editor#456]
On my M1 Mac with macOS 12.5 I have installed the newest Eclipse Modeling (Version: 2022-06 (4.24.0)) with the JustJ JRE (org.eclipse.justj.openjdk.hotspot.jre.full.macosx.aarch64_17.0.2.v20220201-1208) installed via the Eclipse installer. 

When I try to run the Preview or PDF generation of an AsciiDoc file I initially only got the following error in the console:

">> ASP Server at port 4444 exited with code:Some common error happened:1"

After enabling the option "ASP Server output shown in console" I got a more concrete output:

"The operation couldn't be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java."

Is this the expected behavior and if so, is there a possibility to point AsciiDoctor to the JustJ JRE? Or do I have to install an additional JRE for AsciiDoctor to work?

**Comment by de-jcup** [comment]
Hello. 
The asciidoctor editor plugin starts an ASP server in the background. To start this server a JRE is necessary.
Per default the command to start the ASP server is just a simple "java -jar ...." so it uses the installed JRE instance.

If you have no JRE installed this cannot work - so it is an expected behavior.
But... inside the preferences (see next figure) you can define a JRE location - and you can simply point here to the JRE from your eclipse installation. 

Another option would be to create an system wide alias  "java" which points to this location and it will work as well.

![image](https://user-images.githubusercontent.com/11644753/183263222-e18d09d4-8fd3-43c0-90d7-492f18805024.png)

**Comment by dkaiser59** [comment]
Thank you very much for the fast reply, setting the "Path to Java binary" to the location of the JustJ did work for me. 

Is there some way for asciidoctor to detect this kind of configuration (since I assume that more people will just use the eclipse installer instead of installing a JRE/JDK before installing Eclipse) or is this something that should be handled differently by the JustJ JRE of Eclipse?

**Comment by de-jcup** [comment]
> Thank you very much for the fast reply, setting the "Path to Java binary" to the location of the JustJ did work for me.
> 
> Is there some way for asciidoctor to detect this kind of configuration (since I assume that more people will just use the eclipse installer instead of installing a JRE/JDK before installing Eclipse) or is this something that should be handled differently by the JustJ JRE of Eclipse?

Thank you for the idea - created #458 for this.
