### ISSUE TITLE
XIncludes are sometimes shown as Unresolved directive in preview

### ISSUE THREAD

**Issue by vogella** [de-jcup/eclipse-asciidoctor-editor#71]
For some, not for all xincludes I see a Unresolved directive in the preview.
Unresolved directive in 001_article.adoc - include::../001_Books_Shared/legalnotice.adoc[]

Example:
````
= Distributed Version Control with Git
:toclevels: 4
:toc-title:
:linkcss:
:sectnums:
:show-link-uri:  
:experimental:
:icons:
:revnumber: 5. Edition
:chapter-label:
:textselfreference: script
:section-label: {sectnum} {secttitle}
:physical-page-numbers:
////
:media: prepress
////
Lars Vogel, (c) 2009, 2017 vogella GmbH
Version 15.2, 27.01.2017

////
Mastering the Git version control system

<dedication> For my parents Otfried and Mira  </dedication> 
:imagesdir:./img
include::004_foreword.adoc[] 
include::006_preface.adoc[] 
////

include::../001_Books_Shared/legalnotice.adoc[]

= Introduction into Git

:imagesdir: ../com.vogella.tutorials.technology/Git/img
include::../com.vogella.tutorials.technology/Git/001_overview.adoc[]
````
In both includes I can navigate.

![image](https://user-images.githubusercontent.com/139910/40610574-3a6a90c4-6273-11e8-978a-21834de353d7.png)

**Comment by de-jcup** [comment]
Does I get it correctly:
- You have one include ("legalnotice.adoc") which is NOT included/found
- You got another include ("001_overview.adoc") which is correctly included
- The navigation (hyperlinking) does work for both
?
Hm... Normally I just try to resolve the root folder for includes and asciidoc does all other stuff. So a little bit odd when it only finds one but not the other one. Have you not those problems when you are using Gradle/Maven for asciidoc generation?

Please do me a favor and create a zipfile and copy the relevant parts in same file structure as you use it
For example:
```
/src/docs/001_Books_Shared/legalnotice.adoc
/src/docs/001_article.ado
/src/docs/com.vogella.tutorials.technology/Git/001_overview.adoc[]
...
```
and attach it to this issue. So I can just extract it and have the same situation...

Otherwise I am having problems to recreate the problem when I do not know your file structure and where your documents are located.

_If you don't mind I would add your example files to testscript folder._

**Comment by vogella** [comment]
Small example in which the preview does not work attached.
[example.zip](https://github.com/de-jcup/eclipse-asciidoctor-editor/files/2045173/example.zip)

Gradle inclusion works fine.

**Comment by de-jcup** [comment]
The bug is fixed but there is a big need of refactoring (see commit comment)

**Comment by de-jcup** [comment]
Started refactoring approach in feature  branch with commit b986ff6ebce0ee44366a4a62980063d2cb65a07b (missing tag) so mentioning here.
